---
title: "Research Question 1"
subtitle: "Correlations among RTG and ATG" 
author: "R. Noah Padgett"
date: "2021-08-13"
output: html_document
---

```
Research Question 1:

Does authoritarian vs benevolent relationship with God correlate with attachment to God style in cohort 1 and 2?
```


```{r setup, include=FALSE, message=F, error=F, warning=F}

source("code/load_packages.R")
options(digits=3)
```

Read in data

```{r read-data}
# Load imputed data
load("data/imp_dat.RData")
imp_dat_c1 <- imputation[[1]]
imp_dat_c2 <- imputation[[2]]
imp_dat_mids <- rbind(imp_dat_c1, imp_dat_c2)

mydata <- readxl::read_xlsx("data/MH & COVID updated.xlsx")

mydata <- mydata[,colnames(mydata) != "filter_$"]

# recoding to correct for errors
# recode all 0's for AUTH or BENE as NA
mydata$AUTH[mydata$AUTH == 0] <- NA
mydata$BENE[mydata$BENE == 0] <- NA

mydata <- mydata %>%
  group_by(COHORT) %>%
  mutate(
    BENE.z = (BENE - mean(BENE, na.rm=T))/(sd(BENE, na.rm=T))
  )

myVar <- c("COHORT","COVID", "AUTH", "BENE","BENE.z",  "AGIANX", "AGIAVOID", "DEPR", "DEPR_DIAG", "ANX", "ANX_DIAG", "AGI_SECURITY")

subdat <- mydata %>%
  dplyr::select(ID, COHORT, COVID, AUTH, BENE, BENE.z, AGIANX, AGIAVOID, DEPR, DEPR_DIAG, ANX, ANX_DIAG, AGI_SECURITY) 
subdat$flag = 0
i <- 1
for(i in 1:nrow(subdat)){
  subdat$flag[i] = anyNA(subdat[i,-c(1:3)])
}
subdat <- subdat %>%
  filter(flag == 0)


subdat$Cohort = factor(subdat$COHORT, levels=1:2, labels=c("MH-COVID", "ATG"))

```

# Approach 1 - Listwise Deletion

Missing data are listwise deleted - using all cases with complete data on all variables of interest.

```{r}

GGally::ggpairs(
  subdat,  columns = c(4:8),
  mapping = ggplot2::aes(colour=Cohort, alpha=0.75))


p1 <- ggplot(subdat, aes(x=BENE, color=Cohort, fill=Cohort))+
  geom_density(alpha=0.5) +
  scale_color_grey()+
  scale_fill_grey()+
  theme_classic()+theme(legend.position = "none")
p2 <- ggplot(subdat, aes(x=Cohort, y=BENE, color=Cohort, fill=Cohort))+
  geom_boxplot(alpha=0.5) +
  scale_color_grey()+
  scale_fill_grey()+
  theme_classic()
p <- p1 + p2
p

```

## Cohort 1: MH-COVID

```{r}
# Cohort 1
pairs(~AUTH + BENE + AGIANX + AGIAVOID, data=filter(subdat, COHORT==1))
# Authoritarian
cor.test(~AUTH + AGIANX, data=filter(subdat, COHORT==1))
cor.test(~AUTH + AGIAVOID, data=filter(subdat, COHORT==1))
# Benevelant
cor.test(~BENE + AGIANX, data=filter(subdat, COHORT==1))
cor.test(~BENE + AGIAVOID, data=filter(subdat, COHORT==1))
```

## Cohort 2: ATG

```{r}
# Cohort 2
pairs(~AUTH + BENE + AGIANX + AGIAVOID, data=filter(subdat, COHORT==2))
# Authoritarian
cor.test(~AUTH + AGIANX, data=filter(subdat, COHORT==2))
cor.test(~AUTH + AGIAVOID, data=filter(subdat, COHORT==2))
# Benevelant
cor.test(~BENE + AGIANX, data=filter(subdat, COHORT==2))
cor.test(~BENE + AGIAVOID, data=filter(subdat, COHORT==2))
```




# Approach 2 - Single Complete Imputation

A single complete dataset is used

```{r}

GGally::ggpairs(
  imp_dat,  columns = c("AUTH", "BENE", "AGIANX", "AGIAVOID"),
  mapping = ggplot2::aes(colour=Cohort, alpha=0.75))


p1 <- ggplot(subdat, aes(x=BENE, color=Cohort, fill=Cohort))+
  geom_density(alpha=0.5) +
  scale_color_grey()+
  scale_fill_grey()+
  theme_classic()+theme(legend.position = "none")
p2 <- ggplot(subdat, aes(x=Cohort, y=BENE, color=Cohort, fill=Cohort))+
  geom_boxplot(alpha=0.5) +
  scale_color_grey()+
  scale_fill_grey()+
  theme_classic()
p <- p1 + p2
p

```

## Cohort 1

```{r}

# Authoritarian
cor.test(~AUTH + AGIANX, data=filter(imp_dat, COHORT==1))
cor.test(~AUTH + AGIAVOID, data=filter(imp_dat, COHORT==1))
# Benevelant
cor.test(~BENE + AGIANX, data=filter(imp_dat, COHORT==1))
cor.test(~BENE + AGIAVOID, data=filter(imp_dat, COHORT==1))
```

## Cohort 2

```{r}
# Authoritarian
cor.test(~AUTH + AGIANX, data=filter(imp_dat, COHORT==2))
cor.test(~AUTH + AGIAVOID, data=filter(imp_dat, COHORT==2))
# Benevelant
cor.test(~BENE + AGIANX, data=filter(imp_dat, COHORT==2))
cor.test(~BENE + AGIAVOID, data=filter(imp_dat, COHORT==2))
```


# Approach 3 - Full Imputation Method

## Cohort 1

```{r}
c1 <- with(
  imp_dat_c1,
  lm(scale(AUTH)~ scale(AGIANX))
)
pool(c1)
summary(D1(c1))
c1 <- with(
  imp_dat_c1,
  lm(scale(AUTH)~ scale(AGIAVOID))
)
pool(c1)
summary(D1(c1))
# Benevelant
c1 <- with(
  imp_dat_c1,
  lm(scale(BENE)~ scale(AGIANX))
)
pool(c1)
summary(D1(c1))
c1 <- with(
  imp_dat_c1,
  lm(scale(BENE)~ scale(AGIAVOID))
)
pool(c1)
summary(D1(c1))
```

## Cohort 2

```{r}

c1 <- with(
  imp_dat_c2,
  lm(scale(AUTH)~ scale(AGIANX))
)
pool(c1)
summary(D1(c1))
c1 <- with(
  imp_dat_c2,
  lm(scale(AUTH)~ scale(AGIAVOID))
)
pool(c1)
summary(D1(c1))
# Benevelant
c1 <- with(
  imp_dat_c2,
  lm(scale(BENE)~ scale(AGIANX))
)
pool(c1)
summary(D1(c1))
c1 <- with(
  imp_dat_c2,
  lm(scale(BENE)~ scale(AGIAVOID))
)
pool(c1)
summary(D1(c1))

```


## Test Difference Between Cohorts

```{r}
c0 <- with(imp_dat_mids, lm(scale(AUTH)~ scale(AGIANX)+I(COHORT == 1)))
c1 <- with(
  imp_dat_mids,
  lm(scale(AUTH)~ scale(AGIANX)*I(COHORT == 1))
)
pool(c1)
summary(D1(c1, c0))
c0 <- with(imp_dat_mids, lm(scale(AUTH)~ scale(AGIAVOID)+I(COHORT == 1)))
c1 <- with(
  imp_dat_mids,
  lm(scale(AUTH)~ scale(AGIAVOID)*I(COHORT == 1))
)
pool(c1)
summary(D1(c1, c0))
# Benevelant
c0 <- with(imp_dat_mids, lm(scale(BENE.z)~ scale(AGIANX)+I(COHORT == 1)))
c1 <- with(
  imp_dat_mids,
  lm(scale(BENE.z)~ scale(AGIANX)*I(COHORT == 1))
)
pool(c1)
summary(D1(c1,c0))
c0 <- with(imp_dat_mids, lm(scale(BENE.z)~ scale(AGIAVOID)+I(COHORT == 1)))
c1 <- with(
  imp_dat_mids,
  lm(scale(BENE.z)~ scale(AGIAVOID)*I(COHORT == 1))
)
pool(c1)
summary(D1(c1,c0))

```


