---
title: "Research Question 4"
subtitle: "Attachment and Mental Health" 
author: "R. Noah Padgett"
date: "2021-08-13"
output: html_document
---

```
Research Question 4:

Do students with secure attachment score experience less anxiety or depression comparing those with a positive COVID test?
```

```{r setup, include=FALSE, message=F, error=F, warning=F}

source("code/load_packages.R")
options(digits=3)
```

Read in data

```{r read-data}
# Load imputed data
load("data/imp_dat.RData")
imp_dat_c1 <- imputation[[1]]
imp_dat_c2 <- imputation[[2]]
imp_dat_mids <- rbind(imp_dat_c1, imp_dat_c2)

mydata <- readxl::read_xlsx("data/MH & COVID updated.xlsx")

mydata <- mydata[,colnames(mydata) != "filter_$"]

# recoding to correct for errors
# recode all 0's for AUTH or BENE as NA
mydata$AUTH[mydata$AUTH == 0] <- NA
mydata$BENE[mydata$BENE == 0] <- NA

mydata <- mydata %>%
  group_by(COHORT) %>%
  mutate(
    BENE.z = (BENE - mean(BENE, na.rm=T))/(sd(BENE, na.rm=T))
  )

myVar <- c("COHORT","COVID", "AUTH", "BENE","BENE.z",  "AGIANX", "AGIAVOID", "DEPR", "DEPR_DIAG", "ANX", "ANX_DIAG", "AGI_SECURITY")

subdat <- mydata %>%
  dplyr::select(ID, COHORT, COVID, AUTH, BENE, BENE.z, AGIANX, AGIAVOID, DEPR, DEPR_DIAG, ANX, ANX_DIAG, AGI_SECURITY) 
subdat$flag = 0
i <- 1
for(i in 1:nrow(subdat)){
  subdat$flag[i] = anyNA(subdat[i,-c(1:3)])
}
subdat <- subdat %>%
  filter(flag == 0)


subdat$Cohort = factor(subdat$COHORT, levels=1:2, labels=c("MH-COVID", "ATG"))


```


# Creating Attachment Groups

```{r}


subdat %>%
  summarise(
    AGIANX = mean(AGIANX),
    AGIAVOID = mean(AGIAVOID)
  )

subdat <- subdat%>%
  mutate(
    AGI_SECURITY = factor(AGI_SECURITY, levels=1:4, labels=c("Insecure","Avoid", "Anxious","Secure"))
  )

p <- ggplot(subdat, aes(x=AGIANX, y=AGIAVOID, color=AGI_SECURITY))+
  geom_point()+
  geom_vline(xintercept = 34.4)+
  geom_hline(yintercept = 23.7)+
  theme_classic()
p


```

# Approach 1 - Listwise deletion

## Depression Scores

```{r}

out <- summary(aov(DEPR ~ Cohort + AGI_SECURITY + Cohort:AGI_SECURITY, data=subdat))
out
p.adjust(out[[1]]$`Pr(>F)`,method = "fdr")

```


## Anxiety Scores

```{r}

out <- summary(aov(ANX ~ Cohort + AGI_SECURITY + Cohort:AGI_SECURITY, data=subdat))
out
p.adjust(out[[1]]$`Pr(>F)`,method = "fdr")
```

# Approach 2 - Complete Case

## Depression Scores

```{r}

out <- summary(aov(DEPR ~ Cohort + AGI_SECURITY + Cohort:AGI_SECURITY, data=imp_dat))
out
p.adjust(out[[1]]$`Pr(>F)`,method = "fdr")

```

## Anxiety Scores

```{r}

out <- summary(aov(ANX ~ Cohort + AGI_SECURITY + Cohort:AGI_SECURITY, data=imp_dat))
out
p.adjust(out[[1]]$`Pr(>F)`,method = "fdr")

```


# Approach 3 - MI

## Depression Scores

```{r}

out <- mi.anova(mi.res=imp_dat_mids, formula = "DEPR ~ Cohort*as.factor(AGI_SECURITY)", type=3)
p.adjust(out$anova.table$`Pr(>F)`,method = "fdr")

```

## Anxiety Scores

```{r}

out <- mi.anova(mi.res=imp_dat_mids, formula = "ANX ~ Cohort*as.factor(AGI_SECURITY)", type=3)
p.adjust(out$anova.table$`Pr(>F)`,method = "fdr")

```
